services:
  postgres:
    image: postgres:16
    container_name: pet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: petdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d petdb"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
