name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          POSTGRES_DB: petdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U app -d petdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: false
        env:
          TAR_OPTIONS: --skip-old-files  # на всякий случай подавляем tar-ошибки

      - name: sqlc generate
        run: |
          curl -sSLo /usr/local/bin/sqlc https://github.com/sqlc-dev/sqlc/releases/latest/download/sqlc_linux_amd64
          chmod +x /usr/local/bin/sqlc
          sqlc generate
      - name: Build
        run: go build ./...
      - name: Test
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: app
          PGPASSWORD: app
          PGDATABASE: petdb
        run: go test -v ./...
